characters:
  - Harry High-Stakes
  - Henrietta High-Stakes
  - Gambling Jack
  - Anna Belle
  - Mitch Maverick
  - Holly Hickok
  - Montgomery Money
  - Elizabeth Money
  - Minnie Money
  - Banker Bob
  - Banker Bonnie
  - Jesse Wales
  - Poker Alice
  - Sheriff Sam
  - Marshal Dalton
  - Sally Starr
  - Taffy Garrette
  - Barb Cassidy
  - Billy the Bartender

questions:
  - id: name
    text: "What's your name?"
    type: dropdown
  - id: accuse
    text: "Who do you accuse of murder?"
    type: dropdown
  - id: why
    text: "Why do you accuse them?"
    type: text
  - id: best_dressed
    text: "Who was best dressed?"
    type: dropdown
  - id: best_actor
    text: "Who was the best actor/actress?"
    type: dropdown
  - id: money
    text: "How much money did you end with?"
    type: text
  - id: how_money
    text: "How did you get/lose your money?"
    type: text
